config/routes.rb
Rails.application.routes.draw do
  resources :trucks
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "map#index"

  get "/trucks-simple", to: "trucks#simple"
  get "/trucks-delete", to: "trucks#destroyall"
  get "/map", to: "map#index"


  # Session routes
  get "signup", to: "users#new"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  resources :users, except: [:new]
  post "/save-subscription", to: "notifications#subscribe"
  post "/add-subscription", to: "notifications#subtruck"
  post "/remove-subscription", to: "notifications#unsubtruck"
  post "/unsubscribe", to: "notifications#unsubscribe"
  get "/notify", to: "notifications#notify"

end

app/models/truck.rb
class Truck < ApplicationRecord
  # Truck validations before it saves to database
  validates :name, presence: true
  validates :longitude, presence: true
  validates :latitude, presence: true
  validates :schedule, presence: true
  validates :website, presence: true
  validates :menu, presence: true
  validates :longitude, numericality: {in: -106..-104}
  validates :latitude, numericality: {in: 38..40}
end

app/controllers/trucks_controller.rb
class TrucksController < ApplicationController
  before_action :set_truck, only: %i[ show edit update destroy ]
  before_action :require_user, :except => [ :index, :simple, :show ]

  # GET /trucks or /trucks.json
  def index
    @trucks = Truck.all
  end

  # GET /trucks-simple or /trucks-simple.json
  def simple
    @trucks = Truck.all
  end

  # GET /trucks/1 or /trucks/1.json
  def show
  end

  
  # GET /trucks/new
  def new
    @truck = Truck.new
  end

  # GET /trucks/1/edit
  def edit
  end

  # POST /trucks or /trucks.json
  def create
    @truck = Truck.new(truck_params)

    respond_to do |format|
      if @truck.save
        format.html { redirect_to truck_url(@truck), notice: "Truck was successfully created." }
        format.json { render :show, status: :created, location: @truck }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @truck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trucks/1 or /trucks/1.json
  def update
    respond_to do |format|
      if @truck.update(truck_params)
        format.html { redirect_to truck_url(@truck), notice: "Truck was successfully updated." }
        format.json { render :show, status: :ok, location: @truck }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @truck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trucks/1 or /trucks/1.json
  def destroy
    @truck.destroy

    respond_to do |format|
      format.html { redirect_to trucks_url, notice: "Truck was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def destroyall
    if Figaro.env.TESTING == "true"
      @trucks = Truck.all
      @trucks.each do |truck|
        truck.destroy
      end

      respond_to do |format|
        format.html { redirect_to trucks_url, notice: "All trucks destroyed" }
        format.json { head :no_content }
      end
    else
      redirect_to trucks_url, notice: "You are not authorized to do that."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_truck
      @truck = Truck.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def truck_params
      params.require(:truck).permit(:name, :schedule, :website, :longitude, :latitude, :menu)
    end
end

app/helpers/trucks_helper.rb
module TrucksHelper
    def format_schedule(x)
        t = JSON.parse(x)
        w = ""
        if t["Monday"] === true
          w += "Mon. "
        end
        if t["Tuesday"] === true
          w += "Tues. "
        end
        if t["Wednesday"] === true
            w += "Wed. "
        end
        if t["Thursday"] === true
            w += "Thurs. "
        end
        if t["Friday"] === true
            w += "Fri. "
        end
        if t["Saturday"] === true
            w += "Sat. "
        end
        if t["Sunday"] === true
            w += "Sun. "
        end
          w
    end
    # Jblss888
    # where I got the idea to use this to format the input:
    # https://stackoverflow.com/questions/591939/how-can-i-format-the-value-shown-in-a-rails-edit-field
    #
    #What the schedule input needs to look like
    #'{"Monday": true, "Tuesday": false, "Wednesday": false, "Thursday": false, "Friday": false, "Saturday": false, "Sunday": false}'

end

app/views/trucks/_form.html.erb
<%= form_with(model: truck) do |form| %>
  <% if truck.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(truck.errors.count, "error") %> prohibited this truck from being saved:</h2>

      <ul>
        <% truck.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
  <!--'{"Monday": true, "Tuesday": false, "Wednesday": false, "Thursday": false, "Friday": false, "Saturday": false, "Sunday": false}'-->
  <!--<%days= ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]%>

  Where i got the checkox format:
  https://getbootstrap.com/docs/5.2/forms/checks-radios/#indeterminate

  This Looks very helpful and seems like its exactly what I need
  https://www.learnwithjason.dev/blog/get-form-values-as-json/

  -->

<%= simple_form_for(@truck) do |f| %>
  <%= f.input :schedule, as: :check_boxes, collection: 
  [['Monday', "Monday"], ["Tuesday", "Tuesday"], ["Wednesday", "Wednesday"], 
  ["Thursday","Thursday"], ["Friday","Friday"], ["Saturday","Saturday"], ["Sunday","Sunday"]] %>
  <%= f.button :submit %>
<% end %>

  

  <div>
    <%= form.label :website, style: "display: block" %>
    <%= form.text_field :website %>
  </div>

  <div>
    <%= form.label :longitude, style: "display: block" %>
    <%= form.text_field :longitude %>
  </div>

  <div>
    <%= form.label :latitude, style: "display: block" %>
    <%= form.text_field :latitude %>
  </div>

  <div>
    <%= form.label :menu, style: "display: block" %>
    <%= form.text_field :menu %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/trucks/_navigate.html+phone.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet">
  <link href="https://getbootstrap.com/docs/5.2/assets/css/docs.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body class="p-4 m-0 border-1 bd-example">

<table class=" table table-stiped table-bordered table-hover center" style="width: 100%; font-size: 30px;">
  <thead class= "thread-primary">
  <tr>

  </tr>
  </thead>
  <tbody>
  <% Truck.all.each do |truck| %>
    <tr class="table-primary table-striped">
    </tr>
  <% end %>
  </tbody>
</table>

<ul class="nav flex-column justify-content-end ">
  <li class="nav-link dark-link" style="font-size: 20px; font-weight: bold; padding: 0px">
    <a class="nav-link" href="/map.html">Map</a>
  </li>
  <li class="nav-link dark-link" style="font-size: 20px; font-weight: bold; padding: 0px">
    <a class="nav-link" href="/trucks.html">Truck's List</a>
  </li>
  <li class="nav-link dark-link" style="font-size: 20px; font-weight: bold; padding: 0px">
    <a class="nav-link" href="/trucks-simple.html">Simple View</a>
  </li>
</ul>
</body>
</html>

app/views/trucks/_navigate.html.erb
<!--Template from Bootstrap-->
<!--Contains the links to make navigating truck's view easier-->

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://getbootstrap.com/docs/5.2/assets/css/docs.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"></script>
  </head>
  <body class="p-4 m-0 border-1 bd-example">
    <ul class="nav justify-content-end">
    <li class="nav-link dark-link">
        <a class="nav-link" href="/map.html">Map</a>
    </li>
    <li class="nav-link dark-link">
        <a class="nav-link" href="/trucks.html">Truck's List</a>
    </li>
    <li class="nav-link dark-link">
        <a class="nav-link" href="/trucks-simple.html">Simple View</a>
    </li>
    </ul>
  </body>
</html>

app/views/trucks/_truck.html+phone.erb
<div id="<%= dom_id truck %>">

  <p style="font-size: 20px">
    <strong>Schedule:</strong>
    <%=  format_schedule(truck.schedule) %>
  </p>

  <p style="font-size: 20px">
    <strong>Website:</strong>
    <%= truck.website %>
  </p>

  <p style="font-size: 20px">
    <strong>Longitude:</strong>
    <%= truck.longitude %>
  </p>

  <p style="font-size: 20px">
    <strong>Latitude:</strong>
    <%= truck.latitude %>
  </p>

  <p style="font-size: 20px">
    <strong>Menu:</strong>
    <%= truck.menu %>
  </p>

</div>

app/views/trucks/_truck.html.erb
<div id="<%= dom_id truck %>">
  <p>
    <strong>Name:</strong>
    <%= truck.name %>
  </p>

  <p>
    <strong>Schedule:</strong>
    <%=  truck.schedule %>
  </p>

  <p>
    <strong>Website:</strong>
    <%= truck.website %>
  </p>

  <p>
    <strong>Longitude:</strong>
    <%= truck.longitude %>
  </p>

  <p>
    <strong>Latitude:</strong>
    <%= truck.latitude %>
  </p>

  <p>
    <strong>Menu:</strong>
    <%= truck.menu %>
  </p>

</div>

app/views/trucks/edit.html.erb
<h1>Editing truck</h1>
<%= render 'trucks/navigate'%>

<% if logged_in? %>
  <%= render "form", truck: @truck %>

  <br>

  <div>
    <%= link_to "Show this truck", @truck %> |
    <%= link_to "Back to trucks", trucks_path %>
  </div>
<% end %>

app/views/trucks/index.html+phone.erb
<style>
    h1 {text-align: center;}
    h3 {text-align: center;}
    p {text-align: center;}
    div {text-align: center;}
</style>

<p style="color: green"><%= notice %></p>

<h1><span style="font-size: 144%; ">Trucks</span></h1>

<% if logged_in? %>
  <%= link_to "Simple view", "/trucks-simple", class: "mobileview" %>
  <%= link_to "Delete all trucks", "/trucks-delete", class: "mobileview" %>
  <div id="trucks">
    <% @trucks.each do |truck| %>
      <%= render truck %>
      <p>
        <%= link_to "Show this truck", truck, class: "mobileview" %>
      </p>
    <% end %>
  </div>

  <%= link_to "New truck", new_truck_path %>
<% end %>

<% if logged_in? %>
  <%= button_to 'Admin Log Out', logout_path(current_user), method: :delete %>
<%  else %>
  <%= button_to 'Admin Log In', login_path, method: :get  %>
  <%= button_to 'Admin Sign Up', signup_path, method: :get %>
<% end %>

app/views/trucks/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Trucks</h1>

<%= render 'trucks/navigate'%>

<div id="trucks">
  <% @trucks.each do |truck| %>
    <%= render truck %>
    <p>
      <%= link_to "Show this truck", truck %>
    </p>
  <% end %>
</div>
<% if logged_in? %>
  <%= button_to "New truck", new_truck_path, method: :get %>
  <%= button_to "Delete all trucks", "/trucks-delete", method: :get %>
<% end %>

<% if logged_in? %>
  <%= button_to 'Admin Log Out', logout_path(current_user), method: :delete %>
<%  else %>
  <%= button_to 'Admin Log In', login_path, method: :get  %>
  <%= button_to 'Admin Sign Up', signup_path, method: :get %>
<% end %>

app/views/trucks/new.html.erb
<div class= "title-container">
 <h1>New truck</h1>
<div>
<div>
  <%= link_to "Back to trucks", trucks_path %>
</div>

<% if logged_in? %>
  <div class="panel panel-default">
  <div class="panel-body">
  <%= render "form", truck: @truck %>

  <br>


  <div>
  <div>
<% end %>

app/views/trucks/show.html+phone.erb
<h1> <%=@truck.name%></h1>

<body style="background-color: #cfbe8d;">

<div class="dropdown">
  <button class="btn btn-lg dropdown-toggle " type="button" data-bs-toggle="dropdown" aria-expanded="true" align="center">
    <h2>
      Navigation
    </h2>

  </button>
  <ul class="dropdown-menu">
    <%= render 'trucks/navigate'%>
  </ul>
</div>

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>



<div id = "table">
  <%= render @truck %>
</div>



<div style="font-size: 15px">
  <% if logged_in? %>
    <%= link_to "Edit this truck", edit_truck_path(@truck) %> |
  <% end %>
  <%= link_to "Back to trucks", trucks_path %> |
  <%= link_to "Back to trucks (simple view)", "/trucks-simple" %>
  <% if logged_in? %>
    <%= button_to "Destroy this truck", @truck, method: :delete %>
  <% end %>
</div>
<span data-controller="trucks--show"></span>

app/views/trucks/show.html.erb
<h1> <%=@truck.name%></h1>
<%= render 'trucks/navigate'%>
<div id = "table">
  <%= render @truck %>
</div>
  <div>
    <% if logged_in? %>
      <%= link_to "Edit this truck", edit_truck_path(@truck) %> |
    <% end %>
    <%= link_to "Back to trucks", trucks_path %>
    <%= link_to "Back to trucks (simple view)", "/trucks-simple" %>
    <% if logged_in? %>
      <%= button_to "Destroy this truck", @truck, method: :delete %>
    <% end %>
  </div>
<span data-controller="trucks--show"></span>

app/views/trucks/simple.html.erb
<p style="color: green"><%= notice %></p>

<h1>Trucks</h1>
<%= render 'trucks/navigate'%>



<%= link_to "Back to complex view", trucks_path %>

<div id="trucks">
  <% @trucks.each do |truck| %>
    <p>
      <%= link_to ("Name: " + truck.name + " Longitude: " + truck.longitude.to_s + " Latitude: " + truck.latitude.to_s), truck %>
    </p>
  <% end %>
</div>

<% if logged_in? %>
  <%= link_to "New truck", new_truck_path %>
<% end %>